const YEAR_START_MONTH = 0;
const YEAR_START_DAY = 1;

document.addEventListener('DOMContentLoaded', function() {
    var report = document.querySelector('body');
    var _start = new Date(_year, YEAR_START_MONTH, YEAR_START_DAY);
    var _end = new Date(_year + 1, YEAR_START_MONTH, YEAR_START_DAY).lessThan();

    report.appendChild(createDiv('header', _year + ' Report'));

    BBClockAPI.fetchPunches(_start, _end).then((workTimes) => {
        report.appendChild(createDiv('', 'Percentage of Year: ' + workTimes.percent(_start, _end, ['DEFAULT']) + '%'));

        // Report for each month.
        for(var month = 0; month <= 12; month++) {
            var start = new Date(_year, month, 1);
            var end = new Date(_year, month + 1, 1).lessThan();
            if(month == 0) {
                start = new Date(_year, 0, YEAR_START_DAY);
            }
            else if(month == 11) {
                end = new Date(_year + 1, 0, 1).lessThan();
            }
            else if(month == 12) {
                start = new Date(_year + 1, 0, 1);
                end = new Date(_year + 1, 0, YEAR_START_DAY).lessThan();
            }
            var percent = workTimes.percent(start, end, ['DEFAULT']);
            if(percent == '0.000') continue;

            var monthDiv = document.createElement('div');
            monthDiv.classList.add('month');
            monthDiv.appendChild(createDiv('header', start.getMonthString() + ' ' + start.getFullYear()));
            monthDiv.appendChild(createDiv('', 'Percentage of Month: ' + percent + '%'));

            workTimes.forEachOverlapping(start, end, (workTime) => {
                var punchDiv = document.createElement('div');
                punchDiv.classList.add('punch');
                punchDiv.appendChild(createDiv('header', getMilitaryDate(workTime.in) + " - " + getMilitaryDate(workTime.out)));

                punchDiv.appendChild(createDiv('item', 'Duration: ' + workTime.duration().toFixed(3) + ' hours'));
                punchDiv.appendChild(createDiv('item', 'Type: ' + (workTime.in.assoc == 'DEFAULT' ? 'PLACEMENT' : workTime.in.assoc)));
                punchDiv.appendChild(createDiv('item', 'Overnight: ' + (workTime.isOvernight() ? 'Yes' : 'No')));

                monthDiv.appendChild(punchDiv);
            }, ['DEFAULT']);

            report.appendChild(monthDiv);
        }

        report.appendChild(createDiv('footer', 'Report generated by bbclock &copy; 2020 Christopher Bishop.'));
    });
});

function createDiv(className, text) {
    var div = document.createElement('div');
    if(className !== '') div.classList.add(className);
    if(text !== undefined) div.innerHTML = text;
    return div;
}
function getMilitaryDate(punch) {
    return punch.time.toMilitaryTimeString() + " " + punch.time.toYearlessString()
}